from pathlib import Path
from datetime import datetime


class HTMLReport:

    def generate(self, result):

        reports_dir = Path("reports")
        reports_dir.mkdir(exist_ok=True)

        report_file = reports_dir / "report.html"

        html = f"""
<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<title>AI Code Review Report</title>

<style>

body{{
    font-family:Segoe UI,Arial,sans-serif;
    background:#eef2f7;
    margin:0;
    padding:30px;
}}

.container{{
    max-width:1400px;
    margin:auto;
    background:white;
    padding:30px;
    border-radius:12px;
    box-shadow:0 5px 20px rgba(0,0,0,.15);
}}

h1{{
    color:#1f3b63;
}}

h2{{
    color:#1f3b63;
    border-bottom:3px solid #2d8cff;
    padding-bottom:8px;
    margin-top:40px;
}}

.dashboard{{
    display:flex;
    justify-content:space-between;
    gap:20px;
    margin-top:25px;
    margin-bottom:30px;
}}

.card{{
    flex:1;
    background:white;
    border-radius:10px;
    text-align:center;
    padding:20px;
    box-shadow:0 3px 12px rgba(0,0,0,.15);
}}

.card h3{{
    margin:0;
    color:#666;
}}

.card p{{
    font-size:34px;
    color:#0078ff;
    font-weight:bold;
}}

.score{{
    font-size:42px;
    color:green;
    font-weight:bold;
}}

.grade{{
    font-size:30px;
    color:#0078ff;
    font-weight:bold;
}}

table{{
    width:100%;
    border-collapse:collapse;
    margin-bottom:35px;
}}

th,td{{
    border:1px solid #ddd;
    padding:12px;
}}

th{{
    width:180px;
    background:#2d8cff;
    color:white;
}}

pre{{
    background:#272822;
    color:#f8f8f2;
    padding:20px;
    border-radius:10px;
    overflow:auto;
}}

.low{{
    background:#d4edda;
    color:#155724;
    padding:6px 14px;
    border-radius:20px;
    font-weight:bold;
}}

.warning{{
    background:#fff3cd;
    color:#856404;
    padding:6px 14px;
    border-radius:20px;
    font-weight:bold;
}}

.high{{
    background:#f8d7da;
    color:#721c24;
    padding:6px 14px;
    border-radius:20px;
    font-weight:bold;
}}

.footer{{
    text-align:center;
    color:gray;
    margin-top:50px;
}}

</style>

</head>

<body>

<div class="container">

<h1>AI Code Review Report</h1>

<p>
Generated :
{datetime.now()}
</p>

<h2>Dashboard</h2>

<div class="dashboard">

<div class="card">
<h3>Review</h3>
<p>{result["review_score"]}</p>
</div>

<div class="card">
<h3>Security</h3>
<p>{result["security_score"]}</p>
</div>

<div class="card">
<h3>Performance</h3>
<p>{result["performance_score"]}</p>
</div>

<div class="card">
<h3>Documentation</h3>
<p>{result["documentation_score"]}</p>
</div>

</div>

<h2>Overall Score</h2>

<p class="score">
{result["overall_score"]}/100
</p>

<p class="grade">
Grade : {result["grade"]}
</p>

<h2>🔍 Review Agent</h2>

{self.agent_table(result["review"])}

<h2>🔒 Security Agent</h2>

{self.agent_table(result["security"])}

<h2>⚡ Performance Agent</h2>

{self.agent_table(result["performance"])}

<h2>📘 Documentation Agent</h2>

{self.agent_table(result["documentation"])}

<h2>🛠 Repaired Code</h2>

<pre>
{result["repaired_code"]}
</pre>

<h2>📈 Execution Metrics</h2>

<table>

<tr>
<th>Metric</th>
<th>Time</th>
</tr>

<tr>
<td>Review</td>
<td>{result["review_time"]:.2f} sec</td>
</tr>

<tr>
<td>Security</td>
<td>{result["security_time"]:.2f} sec</td>
</tr>

<tr>
<td>Performance</td>
<td>{result["performance_time"]:.2f} sec</td>
</tr>

<tr>
<td>Documentation</td>
<td>{result["documentation_time"]:.2f} sec</td>
</tr>

<tr>
<td>Repair</td>
<td>{result["repair_time"]:.2f} sec</td>
</tr>

<tr>
<td><b>Total</b></td>
<td><b>{result["total_time"]:.2f} sec</b></td>
</tr>

</table>

<div class="footer">

<hr>

<h3>Generated by AI Code Review Assistant</h3>

Powered by Ollama + Qwen2.5

</div>

</div>

</body>

</html>

"""

        report_file.write_text(html, encoding="utf-8")

        print("\nHTML report generated successfully!")
        print(f"Location: {report_file}")

    def agent_table(self, agent):

        severity = agent.severity.lower()

        if severity not in ["low", "warning", "high"]:
            severity = "low"

        return f"""
<table>

<tr>
<th>Severity</th>
<td>

<span class="{severity}">
{agent.severity}
</span>

</td>
</tr>

<tr>
<th>Issue</th>
<td>{agent.issue}</td>
</tr>

<tr>
<th>Explanation</th>
<td>{agent.explanation}</td>
</tr>

<tr>
<th>Suggestion</th>
<td>{agent.suggestion}</td>
</tr>

</table>
"""